server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customerModule
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: orderModule
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**